# Generated by Django 5.2.13 on 2026-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('programme', models.CharField(choices=[('GNM', 'General Nursing & Midwifery (GNM)'), ('ANM', 'Auxiliary Nurse Midwifery (ANM)')], max_length=10)),
                ('board_name', models.CharField(max_length=200)),
                ('passing_year', models.CharField(max_length=4)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.TextField()),
                ('message', models.TextField(blank=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Admission Enquiry',
                'verbose_name_plural': 'Admission Enquiries',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='HostelAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('programme', models.CharField(choices=[('GNM', 'General Nursing & Midwifery (GNM)'), ('ANM', 'Auxiliary Nurse Midwifery (ANM)')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
    ]
